use std::fmt;

use serde::{Deserialize, Serialize};
use serde_yaml::{Mapping, Value};
use sha2::{Digest, Sha256};
use thiserror::Error;
use url::Url;

pub const MAX_PROFILE_BYTES: usize = 2 * 1024 * 1024;

const MAX_YAML_NODES: usize = 100_000;
const MAX_YAML_DEPTH: usize = 64;
const MAX_PROVIDER_NAME_BYTES: usize = 256;
const MAX_PROVIDER_URL_BYTES: usize = 8 * 1024;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Transport {
    System,
    Tun,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DnsMode {
    FakeIp,
    RedirHost,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SanitizeOptions {
    pub mixed_port: u16,
    pub controller_port: u16,
    #[serde(skip_serializing)]
    pub controller_secret: String,
    pub transport: Transport,
    pub dns_mode: DnsMode,
}

impl fmt::Debug for SanitizeOptions {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SanitizeOptions")
            .field("mixed_port", &self.mixed_port)
            .field("controller_port", &self.controller_port)
            .field("controller_secret", &"[redacted]")
            .field("transport", &self.transport)
            .field("dns_mode", &self.dns_mode)
            .finish()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderKind {
    Proxy,
    Rule,
}

impl ProviderKind {
    fn label(self) -> &'static str {
        match self {
            Self::Proxy => "proxy",
            Self::Rule => "rule",
        }
    }
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderDownloadSpec {
    pub kind: ProviderKind,
    pub name: String,
    pub url: String,
    pub cache_path: String,
}

impl fmt::Debug for ProviderDownloadSpec {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ProviderDownloadSpec")
            .field("kind", &self.kind)
            .field("name", &self.name)
            .field("url", &"[redacted]")
            .field("cache_path", &self.cache_path)
            .finish()
    }
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SanitizedProfile {
    pub effective_yaml: String,
    pub provider_downloads: Vec<ProviderDownloadSpec>,
}

impl fmt::Debug for SanitizedProfile {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SanitizedProfile")
            .field("effective_yaml", &"[redacted]")
            .field("provider_downloads", &self.provider_downloads)
            .finish()
    }
}

#[derive(Debug, Error)]
pub enum SanitizeError {
    #[error("profile is {actual} bytes; the limit is {max} bytes")]
    InputTooLarge { actual: usize, max: usize },
    #[error("profile is not valid YAML")]
    InvalidYaml(#[source] serde_yaml::Error),
    #[error("profile root must be a YAML mapping")]
    RootNotMapping,
    #[error("invalid sanitizer options: {0}")]
    InvalidOptions(&'static str),
    #[error("invalid `{section}` section: {reason}")]
    InvalidSection {
        section: &'static str,
        reason: String,
    },
    #[error("unsafe proxy field `{key}` at `{path}`")]
    UnsafeProxyField { path: String, key: String },
    #[error("invalid {kind} provider `{name}`: {reason}")]
    InvalidProvider {
        kind: &'static str,
        name: String,
        reason: &'static str,
    },
    #[error("could not serialize the effective profile")]
    Serialization(#[source] serde_yaml::Error),
}

/// Converts an untrusted subscription profile into a small app-controlled Mihomo profile.
///
/// The controller secret is regenerated by VIA and written only to the managed
/// runtime profile so it never appears in the process command line.
pub fn sanitize_profile(
    input: &[u8],
    options: &SanitizeOptions,
) -> Result<SanitizedProfile, SanitizeError> {
    if input.len() > MAX_PROFILE_BYTES {
        return Err(SanitizeError::InputTooLarge {
            actual: input.len(),
            max: MAX_PROFILE_BYTES,
        });
    }
    validate_options(options)?;

    let source: Value = serde_yaml::from_slice(input).map_err(SanitizeError::InvalidYaml)?;
    enforce_document_budget(&source)?;
    let source = source.as_mapping().ok_or(SanitizeError::RootNotMapping)?;

    let mut provider_downloads = Vec::new();
    let mut effective = app_controlled_base(options);

    copy_proxy_sequence(source, &mut effective, "proxies")?;
    copy_proxy_sequence(source, &mut effective, "proxy-groups")?;
    copy_rules(source, &mut effective)?;
    copy_sub_rules(source, &mut effective)?;

    if let Some(providers) = sanitize_provider_section(
        source,
        "proxy-providers",
        ProviderKind::Proxy,
        &mut provider_downloads,
    )? {
        insert(&mut effective, "proxy-providers", providers);
    }
    if let Some(providers) = sanitize_provider_section(
        source,
        "rule-providers",
        ProviderKind::Rule,
        &mut provider_downloads,
    )? {
        insert(&mut effective, "rule-providers", providers);
    }

    let effective_yaml =
        serde_yaml::to_string(&Value::Mapping(effective)).map_err(SanitizeError::Serialization)?;

    Ok(SanitizedProfile {
        effective_yaml,
        provider_downloads,
    })
}

fn validate_options(options: &SanitizeOptions) -> Result<(), SanitizeError> {
    if options.mixed_port == 0 {
        return Err(SanitizeError::InvalidOptions("mixed_port must not be zero"));
    }
    if options.controller_port == 0 {
        return Err(SanitizeError::InvalidOptions(
            "controller_port must not be zero",
        ));
    }
    if options.mixed_port == options.controller_port {
        return Err(SanitizeError::InvalidOptions(
            "mixed_port and controller_port must be different",
        ));
    }
    if !(32..=128).contains(&options.controller_secret.len())
        || !options
            .controller_secret
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit())
    {
        return Err(SanitizeError::InvalidOptions(
            "controller_secret must be 32-128 hexadecimal characters",
        ));
    }
    Ok(())
}

fn app_controlled_base(options: &SanitizeOptions) -> Mapping {
    let mut effective = Mapping::new();
    insert_number(&mut effective, "mixed-port", options.mixed_port);
    insert_number(&mut effective, "port", 0);
    insert_number(&mut effective, "socks-port", 0);
    insert_number(&mut effective, "redir-port", 0);
    insert_number(&mut effective, "tproxy-port", 0);
    insert_bool(&mut effective, "allow-lan", false);
    insert_string(&mut effective, "bind-address", "127.0.0.1");
    insert_string(&mut effective, "mode", "rule");
    insert_string(&mut effective, "log-level", "warning");
    insert_string(
        &mut effective,
        "external-controller",
        format!("127.0.0.1:{}", options.controller_port),
    );
    insert_string(&mut effective, "secret", options.controller_secret.clone());
    insert(
        &mut effective,
        "tun",
        Value::Mapping(app_controlled_tun(options.transport)),
    );
    insert(
        &mut effective,
        "dns",
        Value::Mapping(app_controlled_dns(options.dns_mode)),
    );
    effective
}

fn app_controlled_tun(transport: Transport) -> Mapping {
    let mut tun = Mapping::new();
    insert_bool(&mut tun, "enable", transport == Transport::Tun);
    insert_string(&mut tun, "stack", "mixed");
    insert_bool(&mut tun, "auto-route", true);
    insert_bool(&mut tun, "auto-detect-interface", true);
    insert_bool(&mut tun, "strict-route", true);
    insert(
        &mut tun,
        "dns-hijack",
        Value::Sequence(vec![
            Value::String("any:53".to_owned()),
            Value::String("tcp://any:53".to_owned()),
        ]),
    );
    tun
}

fn app_controlled_dns(mode: DnsMode) -> Mapping {
    let mut dns = Mapping::new();
    insert_bool(&mut dns, "enable", true);
    insert_bool(&mut dns, "ipv6", false);
    insert_string(
        &mut dns,
        "enhanced-mode",
        match mode {
            DnsMode::FakeIp => "fake-ip",
            DnsMode::RedirHost => "redir-host",
        },
    );
    insert(
        &mut dns,
        "nameserver",
        Value::Sequence(vec![Value::String("system".to_owned())]),
    );

    if mode == DnsMode::FakeIp {
        insert_string(&mut dns, "fake-ip-range", "198.18.0.1/16");
        insert_string(&mut dns, "fake-ip-filter-mode", "blacklist");
        insert(
            &mut dns,
            "fake-ip-filter",
            Value::Sequence(vec![
                Value::String("localhost".to_owned()),
                Value::String("*.lan".to_owned()),
                Value::String("*.local".to_owned()),
            ]),
        );
    }
    dns
}

fn copy_proxy_sequence(
    source: &Mapping,
    effective: &mut Mapping,
    section: &'static str,
) -> Result<(), SanitizeError> {
    let Some(value) = get(source, section) else {
        return Ok(());
    };
    let entries = value
        .as_sequence()
        .ok_or_else(|| invalid_section(section, "must be a sequence"))?;

    for (index, entry) in entries.iter().enumerate() {
        if !entry.is_mapping() {
            return Err(invalid_section(
                section,
                format!("entry {index} must be a mapping"),
            ));
        }
        validate_plain_yaml(entry, section)?;
        reject_unsafe_proxy_fields(entry, &format!("{section}[{index}]"), None)?;
    }

    insert(effective, section, value.clone());
    Ok(())
}

fn copy_rules(source: &Mapping, effective: &mut Mapping) -> Result<(), SanitizeError> {
    let Some(value) = get(source, "rules") else {
        return Ok(());
    };
    validate_rule_list(value, "rules")?;
    insert(effective, "rules", value.clone());
    Ok(())
}

fn copy_sub_rules(source: &Mapping, effective: &mut Mapping) -> Result<(), SanitizeError> {
    let Some(value) = get(source, "sub-rules") else {
        return Ok(());
    };
    let sub_rules = value
        .as_mapping()
        .ok_or_else(|| invalid_section("sub-rules", "must be a mapping"))?;
    for (name, rules) in sub_rules {
        let name = name
            .as_str()
            .ok_or_else(|| invalid_section("sub-rules", "names must be strings"))?;
        if name.is_empty() || name.chars().any(char::is_control) {
            return Err(invalid_section(
                "sub-rules",
                "names must be non-empty and contain no control characters",
            ));
        }
        validate_rule_list(rules, "sub-rules")?;
    }
    insert(effective, "sub-rules", value.clone());
    Ok(())
}

fn validate_rule_list(value: &Value, section: &'static str) -> Result<(), SanitizeError> {
    let rules = value
        .as_sequence()
        .ok_or_else(|| invalid_section(section, "must be a sequence"))?;
    if rules.iter().any(|rule| !rule.is_string()) {
        return Err(invalid_section(section, "every rule must be a string"));
    }
    Ok(())
}

fn sanitize_provider_section(
    source: &Mapping,
    section: &'static str,
    kind: ProviderKind,
    downloads: &mut Vec<ProviderDownloadSpec>,
) -> Result<Option<Value>, SanitizeError> {
    let Some(value) = get(source, section) else {
        return Ok(None);
    };
    let providers = value
        .as_mapping()
        .ok_or_else(|| invalid_section(section, "must be a mapping"))?;

    let mut sanitized = Mapping::new();
    for (raw_name, raw_definition) in providers {
        let name = raw_name
            .as_str()
            .ok_or_else(|| SanitizeError::InvalidProvider {
                kind: kind.label(),
                name: "<non-string>".to_owned(),
                reason: "provider names must be strings",
            })?;
        validate_provider_name(name, kind)?;
        let definition = raw_definition
            .as_mapping()
            .ok_or_else(|| provider_error(kind, name, "definition must be a mapping"))?;
        validate_plain_yaml(raw_definition, section)?;

        let provider_type = string_field(definition, "type")
            .ok_or_else(|| provider_error(kind, name, "type must be a string"))?;
        let definition = match provider_type {
            "http" => sanitize_http_provider(kind, name, definition, downloads)?,
            "inline" => sanitize_inline_provider(kind, name, definition)?,
            "file" => {
                return Err(provider_error(
                    kind,
                    name,
                    "subscription-controlled local file providers are not allowed",
                ));
            }
            _ => {
                return Err(provider_error(
                    kind,
                    name,
                    "only HTTPS http and inline providers are supported",
                ));
            }
        };
        sanitized.insert(Value::String(name.to_owned()), Value::Mapping(definition));
    }

    Ok(Some(Value::Mapping(sanitized)))
}

fn sanitize_http_provider(
    kind: ProviderKind,
    name: &str,
    definition: &Mapping,
    downloads: &mut Vec<ProviderDownloadSpec>,
) -> Result<Mapping, SanitizeError> {
    let raw_url = string_field(definition, "url")
        .ok_or_else(|| provider_error(kind, name, "url must be a string"))?;
    let url = validate_https_provider_url(raw_url)
        .map_err(|reason| provider_error(kind, name, reason))?;

    let (behavior, format, extension) = match kind {
        ProviderKind::Proxy => (None, None, "yaml"),
        ProviderKind::Rule => {
            let behavior = validated_rule_behavior(kind, name, definition)?;
            let format = validated_rule_format(kind, name, definition)?;
            let extension = match format {
                "yaml" => "yaml",
                "text" => "txt",
                "mrs" => "mrs",
                _ => unreachable!("validated_rule_format returned an unknown format"),
            };
            (Some(behavior), Some(format), extension)
        }
    };

    let cache_path = provider_cache_path(kind, name, url.as_str(), extension);
    downloads.push(ProviderDownloadSpec {
        kind,
        name: name.to_owned(),
        url: url.to_string(),
        cache_path: cache_path.clone(),
    });

    let mut sanitized = Mapping::new();
    insert_string(&mut sanitized, "type", "file");
    insert_string(&mut sanitized, "path", cache_path);
    if let Some(behavior) = behavior {
        insert_string(&mut sanitized, "behavior", behavior);
    }
    if let Some(format) = format {
        insert_string(&mut sanitized, "format", format);
    }
    Ok(sanitized)
}

fn sanitize_inline_provider(
    kind: ProviderKind,
    name: &str,
    definition: &Mapping,
) -> Result<Mapping, SanitizeError> {
    let payload = get(definition, "payload")
        .ok_or_else(|| provider_error(kind, name, "inline payload is required"))?;

    match kind {
        ProviderKind::Proxy => {
            let entries = payload
                .as_sequence()
                .ok_or_else(|| provider_error(kind, name, "payload must be a sequence"))?;
            for (index, entry) in entries.iter().enumerate() {
                if !entry.is_mapping() {
                    return Err(provider_error(
                        kind,
                        name,
                        "every payload entry must be a proxy mapping",
                    ));
                }
                validate_plain_yaml(entry, "proxy-providers")?;
                reject_unsafe_proxy_fields(
                    entry,
                    &format!("proxy-providers.{name}.payload[{index}]"),
                    None,
                )?;
            }
        }
        ProviderKind::Rule => validate_rule_list(payload, "rule-providers")?,
    }

    let mut sanitized = Mapping::new();
    insert_string(&mut sanitized, "type", "inline");
    if kind == ProviderKind::Rule {
        insert_string(
            &mut sanitized,
            "behavior",
            validated_rule_behavior(kind, name, definition)?,
        );
    }
    insert(&mut sanitized, "payload", payload.clone());
    Ok(sanitized)
}

fn validated_rule_behavior<'a>(
    kind: ProviderKind,
    name: &str,
    definition: &'a Mapping,
) -> Result<&'a str, SanitizeError> {
    let behavior = string_field(definition, "behavior")
        .ok_or_else(|| provider_error(kind, name, "behavior must be a string"))?;
    match behavior {
        "domain" | "ipcidr" | "classical" => Ok(behavior),
        _ => Err(provider_error(
            kind,
            name,
            "behavior must be domain, ipcidr, or classical",
        )),
    }
}

fn validated_rule_format<'a>(
    kind: ProviderKind,
    name: &str,
    definition: &'a Mapping,
) -> Result<&'a str, SanitizeError> {
    let format = match get(definition, "format") {
        Some(value) => value
            .as_str()
            .ok_or_else(|| provider_error(kind, name, "format must be a string"))?,
        None => "yaml",
    };
    match format {
        "yaml" | "text" | "mrs" => Ok(format),
        _ => Err(provider_error(
            kind,
            name,
            "format must be yaml, text, or mrs",
        )),
    }
}

fn validate_https_provider_url(raw: &str) -> Result<Url, &'static str> {
    if raw.len() > MAX_PROVIDER_URL_BYTES {
        return Err("url is too long");
    }
    let mut url = Url::parse(raw).map_err(|_| "url is invalid")?;
    if url.scheme() != "https" {
        return Err("url must use HTTPS");
    }
    if url.host_str().is_none() || url.cannot_be_a_base() {
        return Err("url must contain a valid host");
    }
    if !url.username().is_empty() || url.password().is_some() {
        return Err("url must not contain embedded credentials");
    }
    if url.fragment().is_some() {
        url.set_fragment(None);
    }
    Ok(url)
}

fn provider_cache_path(
    kind: ProviderKind,
    name: &str,
    normalized_url: &str,
    extension: &str,
) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"via-provider-cache-v1\0");
    hasher.update(kind.label().as_bytes());
    hasher.update(b"\0");
    hasher.update(name.as_bytes());
    hasher.update(b"\0");
    hasher.update(normalized_url.as_bytes());
    let digest = hex::encode(hasher.finalize());
    format!("providers/{}/{digest}.{extension}", kind.label())
}

fn validate_provider_name(name: &str, kind: ProviderKind) -> Result<(), SanitizeError> {
    if name.is_empty() || name.len() > MAX_PROVIDER_NAME_BYTES || name.chars().any(char::is_control)
    {
        return Err(provider_error(
            kind,
            name,
            "name must be non-empty, short, and contain no control characters",
        ));
    }
    Ok(())
}

fn reject_unsafe_proxy_fields(
    value: &Value,
    path: &str,
    parent_key: Option<&str>,
) -> Result<(), SanitizeError> {
    match value {
        Value::Mapping(mapping) => {
            for (raw_key, child) in mapping {
                let key = raw_key.as_str().ok_or_else(|| {
                    invalid_section("proxies", "proxy mappings may only use string keys")
                })?;
                let normalized = normalize_key(key);
                if normalized == "type"
                    && child
                        .as_str()
                        .is_some_and(|value| value.eq_ignore_ascii_case("tailscale"))
                {
                    return Err(SanitizeError::UnsafeProxyField {
                        path: path.to_owned(),
                        key: key.to_owned(),
                    });
                }
                if is_unsafe_proxy_key(&normalized, parent_key) {
                    return Err(SanitizeError::UnsafeProxyField {
                        path: path.to_owned(),
                        key: key.to_owned(),
                    });
                }
                reject_unsafe_proxy_fields(
                    child,
                    &format!("{path}.{key}"),
                    Some(normalized.as_str()),
                )?;
            }
        }
        Value::Sequence(sequence) => {
            for (index, child) in sequence.iter().enumerate() {
                reject_unsafe_proxy_fields(child, &format!("{path}[{index}]"), parent_key)?;
            }
        }
        Value::Tagged(_) => {
            return Err(invalid_section(
                "proxies",
                "YAML tags are not allowed in proxy definitions",
            ));
        }
        _ => {}
    }
    Ok(())
}

fn is_unsafe_proxy_key(key: &str, parent_key: Option<&str>) -> bool {
    if key == "path" {
        return !matches!(parent_key, Some("ws-opts" | "http-opts" | "h2-opts"));
    }

    key.ends_with("-path")
        || matches!(
            key,
            "command"
                | "commands"
                | "cmd"
                | "exec"
                | "executable"
                | "program"
                | "binary"
                | "script"
                | "cwd"
                | "working-dir"
                | "working-directory"
                | "state-dir"
                | "private-key"
                | "private-key-file"
                | "client-key"
                | "client-cert"
                | "certificate"
                | "ca"
                | "ca-file"
                | "unix-socket"
                | "socket"
                | "interface"
                | "interface-name"
                | "routing-mark"
        )
}

fn normalize_key(key: &str) -> String {
    key.trim().to_ascii_lowercase().replace('_', "-")
}

fn validate_plain_yaml(value: &Value, section: &'static str) -> Result<(), SanitizeError> {
    let mut stack = vec![value];
    while let Some(value) = stack.pop() {
        match value {
            Value::Mapping(mapping) => {
                for (key, value) in mapping {
                    if !key.is_string() {
                        return Err(invalid_section(section, "mapping keys must be strings"));
                    }
                    stack.push(value);
                }
            }
            Value::Sequence(sequence) => stack.extend(sequence.iter()),
            Value::Tagged(_) => {
                return Err(invalid_section(section, "YAML tags are not allowed"));
            }
            _ => {}
        }
    }
    Ok(())
}

fn enforce_document_budget(value: &Value) -> Result<(), SanitizeError> {
    let mut nodes = 0usize;
    let mut stack = vec![(value, 0usize)];
    while let Some((value, depth)) = stack.pop() {
        nodes += 1;
        if nodes > MAX_YAML_NODES {
            return Err(invalid_section(
                "document",
                format!("contains more than {MAX_YAML_NODES} YAML nodes"),
            ));
        }
        if depth > MAX_YAML_DEPTH {
            return Err(invalid_section(
                "document",
                format!("nesting exceeds {MAX_YAML_DEPTH} levels"),
            ));
        }
        match value {
            Value::Mapping(mapping) => {
                for (key, value) in mapping {
                    stack.push((key, depth + 1));
                    stack.push((value, depth + 1));
                }
            }
            Value::Sequence(sequence) => {
                stack.extend(sequence.iter().map(|value| (value, depth + 1)));
            }
            Value::Tagged(tagged) => stack.push((&tagged.value, depth + 1)),
            _ => {}
        }
    }
    Ok(())
}

fn string_field<'a>(mapping: &'a Mapping, key: &str) -> Option<&'a str> {
    get(mapping, key).and_then(Value::as_str)
}

fn get<'a>(mapping: &'a Mapping, key: &str) -> Option<&'a Value> {
    mapping.get(Value::String(key.to_owned()))
}

fn insert(mapping: &mut Mapping, key: &str, value: Value) {
    mapping.insert(Value::String(key.to_owned()), value);
}

fn insert_string(mapping: &mut Mapping, key: &str, value: impl Into<String>) {
    insert(mapping, key, Value::String(value.into()));
}

fn insert_bool(mapping: &mut Mapping, key: &str, value: bool) {
    insert(mapping, key, Value::Bool(value));
}

fn insert_number(mapping: &mut Mapping, key: &str, value: u16) {
    insert(mapping, key, Value::Number((value as u64).into()));
}

fn invalid_section(section: &'static str, reason: impl Into<String>) -> SanitizeError {
    SanitizeError::InvalidSection {
        section,
        reason: reason.into(),
    }
}

fn provider_error(kind: ProviderKind, name: &str, reason: &'static str) -> SanitizeError {
    SanitizeError::InvalidProvider {
        kind: kind.label(),
        name: name.to_owned(),
        reason,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn options(transport: Transport, dns_mode: DnsMode) -> SanitizeOptions {
        SanitizeOptions {
            mixed_port: 18_900,
            controller_port: 18_901,
            controller_secret: "a".repeat(64),
            transport,
            dns_mode,
        }
    }

    fn sanitized(yaml: &str, transport: Transport, dns_mode: DnsMode) -> SanitizedProfile {
        sanitize_profile(yaml.as_bytes(), &options(transport, dns_mode)).unwrap()
    }

    fn parse_output(result: &SanitizedProfile) -> Value {
        serde_yaml::from_str(&result.effective_yaml).unwrap()
    }

    fn field<'a>(value: &'a Value, key: &str) -> &'a Value {
        get(value.as_mapping().unwrap(), key).unwrap()
    }

    #[test]
    fn malicious_top_level_overrides_are_replaced_or_removed() {
        let input = r#"
port: 1
socks-port: 2
mixed-port: 3
redir-port: 4
tproxy-port: 5
allow-lan: true
bind-address: "*"
authentication: ["attacker:password"]
external-controller: "0.0.0.0:9090"
secret: subscription-secret
external-ui: C:/attacker/ui
external-ui-url: https://attacker.invalid/ui.zip
external-controller-tls: "0.0.0.0:9443"
tls:
  certificate: C:/attacker/cert.pem
  private-key: C:/attacker/key.pem
tun:
  enable: false
  device: attacker
  route-address: [0.0.0.0/0]
dns:
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver: [https://attacker.invalid/dns-query]
ntp:
  enable: true
iptables: {enable: true}
interface-name: attacker0
routing-mark: 666
geodata-mode: true
geo-auto-update: true
profile: {store-selected: true}
experimental: {quic-go-disable-gso: false}
proxies:
  - {name: safe, type: ss, server: example.com, port: 443, cipher: aes-128-gcm, password: p}
rules: ["MATCH,DIRECT"]
"#;

        let result = sanitized(input, Transport::Tun, DnsMode::FakeIp);
        let output = parse_output(&result);
        let root = output.as_mapping().unwrap();

        assert_eq!(field(&output, "mixed-port").as_u64(), Some(18_900));
        assert_eq!(field(&output, "port").as_u64(), Some(0));
        assert_eq!(field(&output, "socks-port").as_u64(), Some(0));
        assert_eq!(field(&output, "redir-port").as_u64(), Some(0));
        assert_eq!(field(&output, "tproxy-port").as_u64(), Some(0));
        assert_eq!(field(&output, "allow-lan").as_bool(), Some(false));
        assert_eq!(field(&output, "bind-address").as_str(), Some("127.0.0.1"));
        assert_eq!(field(&output, "mode").as_str(), Some("rule"));
        assert_eq!(field(&output, "log-level").as_str(), Some("warning"));
        assert_eq!(
            field(&output, "external-controller").as_str(),
            Some("127.0.0.1:18901")
        );
        assert_eq!(
            field(&output, "secret").as_str(),
            Some("a".repeat(64).as_str())
        );
        assert_eq!(field(field(&output, "tun"), "enable").as_bool(), Some(true));

        for forbidden in [
            "authentication",
            "external-ui",
            "external-ui-url",
            "external-controller-tls",
            "tls",
            "ntp",
            "iptables",
            "interface-name",
            "routing-mark",
            "geodata-mode",
            "geo-auto-update",
            "profile",
            "experimental",
        ] {
            assert!(!root.contains_key(Value::String(forbidden.to_owned())));
        }
        assert!(!result.effective_yaml.contains("subscription-secret"));
        assert!(result.effective_yaml.contains(&"a".repeat(64)));
        assert!(!result.effective_yaml.contains("attacker.invalid"));
    }

    #[test]
    fn https_providers_are_extracted_and_rewritten_to_hashed_relative_files() {
        let input = r#"
proxy-providers:
  paid-nodes:
    type: http
    url: https://provider.example/sub?token=sensitive
    path: C:/attacker/chosen.yaml
    interval: 60
rule-providers:
  private-rules:
    type: http
    url: https://rules.example/list.txt#ignored
    path: ../../escape.txt
    behavior: classical
    format: text
rules: ["RULE-SET,private-rules,DIRECT", "MATCH,paid-nodes"]
"#;

        let result = sanitized(input, Transport::System, DnsMode::FakeIp);
        assert_eq!(result.provider_downloads.len(), 2);
        assert_eq!(result.provider_downloads[0].kind, ProviderKind::Proxy);
        assert_eq!(
            result.provider_downloads[0].url,
            "https://provider.example/sub?token=sensitive"
        );
        assert_eq!(result.provider_downloads[1].kind, ProviderKind::Rule);
        assert_eq!(
            result.provider_downloads[1].url,
            "https://rules.example/list.txt"
        );

        let output = parse_output(&result);
        let proxy_provider = field(field(&output, "proxy-providers"), "paid-nodes");
        let rule_provider = field(field(&output, "rule-providers"), "private-rules");
        for provider in [proxy_provider, rule_provider] {
            assert_eq!(field(provider, "type").as_str(), Some("file"));
            assert!(
                field(provider, "path")
                    .as_str()
                    .unwrap()
                    .starts_with("providers/")
            );
            assert!(
                !provider
                    .as_mapping()
                    .unwrap()
                    .contains_key(Value::String("url".into()))
            );
        }
        assert_eq!(field(rule_provider, "behavior").as_str(), Some("classical"));
        assert_eq!(field(rule_provider, "format").as_str(), Some("text"));
        assert!(
            field(rule_provider, "path")
                .as_str()
                .unwrap()
                .ends_with(".txt")
        );
        assert!(!result.effective_yaml.contains("sensitive"));
        assert!(!result.effective_yaml.contains("C:/attacker"));
        assert!(!result.effective_yaml.contains(".."));
    }

    #[test]
    fn non_https_and_local_file_providers_are_rejected() {
        for input in [
            "proxy-providers:\n  p: {type: http, url: http://example.com/sub}\n",
            "proxy-providers:\n  p: {type: http, url: file:///tmp/sub.yaml}\n",
            "proxy-providers:\n  p: {type: http, url: 'https://user:password@example.com/sub'}\n",
            "proxy-providers:\n  p: {type: file, path: C:/Users/attacker/sub.yaml}\n",
            "proxy-providers:\n  p: {type: ftp, url: https://example.com/sub}\n",
        ] {
            let error = sanitize_profile(
                input.as_bytes(),
                &options(Transport::System, DnsMode::FakeIp),
            )
            .unwrap_err();
            assert!(matches!(error, SanitizeError::InvalidProvider { .. }));
        }
    }

    #[test]
    fn profile_size_is_limited_before_parsing() {
        let oversized = vec![b' '; MAX_PROFILE_BYTES + 1];
        let error =
            sanitize_profile(&oversized, &options(Transport::System, DnsMode::FakeIp)).unwrap_err();
        assert!(matches!(
            error,
            SanitizeError::InputTooLarge {
                actual,
                max: MAX_PROFILE_BYTES
            } if actual == MAX_PROFILE_BYTES + 1
        ));
    }

    #[test]
    fn fake_ip_and_redir_host_templates_are_app_controlled() {
        let malicious_dns =
            "dns: {enhanced-mode: attacker, listen: 0.0.0.0:53}\nrules: [MATCH,DIRECT]\n";

        let fake = sanitized(malicious_dns, Transport::System, DnsMode::FakeIp);
        let fake = parse_output(&fake);
        let fake_dns = field(&fake, "dns");
        assert_eq!(field(fake_dns, "enhanced-mode").as_str(), Some("fake-ip"));
        assert_eq!(
            field(fake_dns, "fake-ip-range").as_str(),
            Some("198.18.0.1/16")
        );
        assert!(
            !fake_dns
                .as_mapping()
                .unwrap()
                .contains_key(Value::String("listen".into()))
        );

        let redir = sanitized(malicious_dns, Transport::Tun, DnsMode::RedirHost);
        let redir = parse_output(&redir);
        let redir_dns = field(&redir, "dns");
        assert_eq!(
            field(redir_dns, "enhanced-mode").as_str(),
            Some("redir-host")
        );
        assert!(
            !redir_dns
                .as_mapping()
                .unwrap()
                .contains_key(Value::String("fake-ip-range".into()))
        );
        assert_eq!(field(field(&redir, "tun"), "enable").as_bool(), Some(true));
    }

    #[test]
    fn filesystem_and_command_keys_are_rejected_recursively_in_proxies() {
        for unsafe_fragment in [
            "plugin-opts: {command: calc.exe}",
            "private-key: C:/Users/attacker/id_ed25519",
            "nested: {certificate-path: /tmp/cert.pem}",
            "interface-name: attacker0",
            "state-dir: C:/ProgramData/attacker",
        ] {
            let input = format!(
                "proxies:\n  - name: bad\n    type: ss\n    server: example.com\n    port: 443\n    cipher: aes-128-gcm\n    password: p\n    {unsafe_fragment}\n"
            );
            let error = sanitize_profile(
                input.as_bytes(),
                &options(Transport::System, DnsMode::FakeIp),
            )
            .unwrap_err();
            assert!(matches!(error, SanitizeError::UnsafeProxyField { .. }));
        }
    }

    #[test]
    fn tailscale_proxy_nodes_are_rejected() {
        let input = r#"
proxies:
  - name: unsafe-stateful-node
    type: tailscale
    auth-key: tskey-example
    state-dir: state
rules: [MATCH,DIRECT]
"#;
        let error = sanitize_profile(input.as_bytes(), &options(Transport::Tun, DnsMode::FakeIp))
            .unwrap_err();
        assert!(matches!(error, SanitizeError::UnsafeProxyField { .. }));
    }

    #[test]
    fn network_request_paths_are_not_mistaken_for_filesystem_paths() {
        let input = r#"
proxies:
  - name: websocket
    type: vmess
    server: example.com
    port: 443
    uuid: 00000000-0000-0000-0000-000000000000
    network: ws
    ws-opts:
      path: /safe/websocket/path
"#;
        let result = sanitized(input, Transport::System, DnsMode::FakeIp);
        assert!(result.effective_yaml.contains("/safe/websocket/path"));
    }

    #[test]
    fn inline_provider_payload_is_retained_but_checked() {
        let safe = r#"
proxy-providers:
  inline-safe:
    type: inline
    payload:
      - {name: node, type: ss, server: example.com, port: 443, cipher: aes-128-gcm, password: p}
"#;
        let result = sanitized(safe, Transport::System, DnsMode::FakeIp);
        assert!(result.provider_downloads.is_empty());
        assert!(result.effective_yaml.contains("inline-safe"));
        assert!(result.effective_yaml.contains("payload"));

        let unsafe_inline = r#"
proxy-providers:
  inline-bad:
    type: inline
    payload:
      - {name: bad, type: ssh, server: example.com, port: 22, private-key: /tmp/key}
"#;
        let error = sanitize_profile(
            unsafe_inline.as_bytes(),
            &options(Transport::System, DnsMode::FakeIp),
        )
        .unwrap_err();
        assert!(matches!(error, SanitizeError::UnsafeProxyField { .. }));
    }
}
